{{ range .cluster_node_instance_groups }}
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  <<: {{ .metadata | toJson }}
  labels:
    <<: {{ default (dict) (get .metadata "labels") | toJson }}
    kops.k8s.io/cluster: {{ $.cluster_name }}
  name: {{ default "nodes" (get .metadata "name") }}
spec:
  <<: {{ .spec | toJson }}
  cloudLabels:
    <<: {{ default (dict) $.aws_provider_default_tags | toJson }}
    service: k8s_node
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/{{ $.cluster_name }}: ""
  role: Node
  kubernetesVersion: {{ $.k8s_version }}
  image: {{ $.cluster_image }}
  subnets:
  {{ range (default $.cluster_availability_zones .availability_zones) }}
  - private-{{ . }}
  {{ end }}
  taints:
  {{ range (default (list) (get .spec "taints")) }}
  - "{{ .key }}={{ .value }}:{{ .effect }}"
  {{ end }}
{{ end }}
