---
apiVersion: iamauthenticator.k8s.aws/v1alpha1
kind: IAMIdentityMapping
metadata:
  name: kubernetes-admin
spec:
  arn: {{ .aws_iam_cluster_admin_role_arn }}
  username: kubernetes-admin
  groups:
  - system:masters
